In [ ]:

# Assignment 3
# Descriptive Statistics - Measures of Central Tendency and variability

# Perform the following operations on any open source dataset (e.g., data.csv)

# Provide summary statistics (mean, median, minimum, maximum, standard deviation) for a dataset (age, income etc.) with numeric variables grouped by one of the qualitative (categorical) variable. For example, if your categorical variable is age groups and quantitative variable is income, then provide summary statistics of income grouped by the age groups. Create a list that contains a numeric value for each response to the categorical variable.
# Write a Python program to display some basic statistical details like percentile, mean, standard deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris- versicolor’ of iris.csv dataset. Provide the codes with outputs and explain everything that you do in this step.

In [11]:
import numpy as np
import pandas as pd

In [12]:
df = pd.read_csv('nba.csv')
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df.isnull().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [14]:
df_new = df.copy()

# Fill 'College' NaNs with 'Not in a college'
df_new['College'] = df_new['College'].fillna('Not in a college')

# Fill 'Salary' NaNs with the mean salary
df_new['Salary'] = df_new['Salary'].fillna(df_new['Salary'].mean())

# Drop any other NaNs
df_new.dropna(inplace=True)

# Check if any NaNs are left
print(df_new.isnull().sum())

Name        0
Team        0
Number      0
Position    0
Age         0
Height      0
Weight      0
College     0
Salary      0
dtype: int64

In [15]:
age_col = ['0-10','11-15','16-20','21-25','26-30','30-40']

age_series = df_new['Age']
for i in range(len(age_series)):
    if age_series[i] < 10: age_series[i] = age_col[0]
    elif age_series[i] < 15: age_series[i] = age_col[1]
    elif age_series[i] < 20: age_series[i] = age_col[2]
    elif age_series[i] < 25: age_series[i] = age_col[3]
    elif age_series[i] < 30: age_series[i] = age_col[4]
    else: age_series[i] = age_col[5]

/tmp/ipykernel_23608/3813253546.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  elif age_series[i] < 30: age_series[i] = age_col[4]
/tmp/ipykernel_23608/3813253546.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '26-30' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  elif age_series[i] < 30: age_series[i] = age_col[4]

In [16]:
age_series.head(20)

0     26-30
1     26-30
2     26-30
3     21-25
4     26-30
5     26-30
6     21-25
7     26-30
8     21-25
9     21-25
10    21-25
11    26-30
12    26-30
13    21-25
14    26-30
15    26-30
16    21-25
17    26-30
18    21-25
19    30-40
Name: Age, dtype: object

In [21]:
df_new['Age'] = df_new['Age'].astype(object)
df1 = df_new.groupby('Age')
df1.head()
# df1.describe()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,26-30,6-2,180.0,Texas,7.730337e+06
1,Jae Crowder,Boston Celtics,99.0,SF,26-30,6-6,235.0,Marquette,6.796117e+06
2,John Holland,Boston Celtics,30.0,SG,26-30,6-5,205.0,Boston University,4.842684e+06
3,R.J. Hunter,Boston Celtics,28.0,SG,21-25,6-5,185.0,Georgia State,1.148640e+06
4,Jonas Jerebko,Boston Celtics,8.0,PF,26-30,6-10,231.0,Not in a college,5.000000e+06
5,Amir Johnson,Boston Celtics,90.0,PF,26-30,6-9,240.0,Not in a college,1.200000e+07
6,Jordan Mickey,Boston Celtics,55.0,PF,21-25,6-8,235.0,LSU,1.170960e+06
8,Terry Rozier,Boston Celtics,12.0,PG,21-25,6-2,190.0,Louisville,1.824360e+06
9,Marcus Smart,Boston Celtics,36.0,PG,21-25,6-4,220.0,Oklahoma State,3.431040e+06
10,Jared Sullinger,Boston Celtics,7.0,C,21-25,6-9,260.0,Ohio State,2.569260e+06
19,Jarrett Jack,Brooklyn Nets,2.0,PG,30-40,6-3,200.0,Georgia Tech,6.300000e+06
30,Arron Afflalo,New York Knicks,4.0,SG,30-40,6-5,210.0,UCLA,8.000000e+06
31,Lou Amundson,New York Knicks,17.0,PF,30-40,6-9,220.0,UNLV,1.635476e+06
33,Carmelo Anthony,New York Knicks,7.0,SF,30-40,6-8,240.0,Syracuse,2.287500e+07
34,Jose Calderon,New York Knicks,3.0,PG,30-40,6-3,200.0,Not in a college,7.402812e+06
122,Devin Booker,Phoenix Suns,1.0,SG,16-20,6-6,206.0,Kentucky,2.127840e+06
226,Rashad Vaughn,Milwaukee Bucks,20.0,SG,16-20,6-6,202.0,UNLV,1.733040e+06

In [19]:
columns = ["Salary"]

for ageGroup, group in df1:
    print(f"Statistics for {ageGroup}:\n")

    for col in columns:
        val = group[col]

        variance = sum((val - val.mean())**2) / len(val)
        deviation = variance**0.5

        print(f"Column: {col}")
        print(f"Variance = {variance}")
        print(f"Standard Deviation = {deviation}")
        print(f"Mean = {val.mean()}")
        print(f"Median = {val.median()}")
        print(f"Min = {val.min()}")
        print(f"Max = {val.max()}")
        print("\n")

Statistics for 16-20:

Column: Salary
Variance = 38966760000.0
Standard Deviation = 197400.0
Mean = 1930440.0
Median = 1930440.0
Min = 1733040.0
Max = 2127840.0


Statistics for 21-25:

Column: Salary
Variance = 10072949806183.27
Standard Deviation = 3173791.077904037
Mean = 2772642.384352136
Median = 1686039.5
Min = 30888.0
Max = 16407501.0


Statistics for 26-30:

Column: Salary
Variance = 29940345630762.883
Standard Deviation = 5471777.191257232
Mean = 5679300.394594058
Median = 3578947.0
Min = 55722.0
Max = 20158622.0


Statistics for 30-40:

Column: Salary
Variance = 34335381343460.676
Standard Deviation = 5859640.035314513
Mean = 6228284.773083144
Median = 4671342.052690582
Min = 200600.0
Max = 25000000.0

In [24]:
df_iris = pd.read_csv('Iris.csv')
df_iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [25]:
df_iris.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [30]:
df_iris.dtypes
df_iris.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [29]:
dfg = df_iris.groupby('Species')
dfg.describe()

                   Id                                                        \
                count   mean       std    min     25%    50%     75%    max
Species
Iris-setosa      50.0   25.5  14.57738    1.0   13.25   25.5   37.75   50.0
Iris-versicolor  50.0   75.5  14.57738   51.0   63.25   75.5   87.75  100.0
Iris-virginica   50.0  125.5  14.57738  101.0  113.25  125.5  137.75  150.0

                SepalLengthCm         ... PetalLengthCm      PetalWidthCm  \
                        count   mean  ...           75%  max        count
Species                               ...
Iris-setosa              50.0  5.006  ...         1.575  1.9         50.0
Iris-versicolor          50.0  5.936  ...         4.600  5.1         50.0
Iris-virginica           50.0  6.588  ...         5.875  6.9         50.0


                  mean       std  min  25%  50%  75%  max
Species
Iris-setosa      0.244  0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 40 columns]

In [36]:
columns = ['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']

for species, group in dfg:
    print(f"Statistics of {species}:\n")

    for col in columns:
        val = group[col]

        variance = sum((val - val.mean())**2) / (len(val))
        deviation = variance**0.5

        print(f"Column: {col}")
        print(f"Variance = {variance}")
        print(f"Standard Deviation = {deviation}")
        print(f"Mean = {val.mean()}")
        print(f"Median = {val.median()}")
        print(f"Min = {val.min()}")
        print(f"Max = {val.max()}")
        print("\n")

Statistics of Iris-setosa:

Column: SepalLengthCm
Variance = 0.12176400000000002
Standard Deviation = 0.3489469873777391
Mean = 5.006
Median = 5.0
Min = 4.3
Max = 5.8


Column: SepalWidthCm
Variance = 0.142276
Standard Deviation = 0.37719490982779713
Mean = 3.418
Median = 3.4
Min = 2.3
Max = 4.4


Column: PetalLengthCm
Variance = 0.029504000000000002
Standard Deviation = 0.17176728442867112
Mean = 1.464
Median = 1.5
Min = 1.0
Max = 1.9


Column: PetalWidthCm
Variance = 0.011263999999999998
Standard Deviation = 0.10613199329137278
Mean = 0.244
Median = 0.2
Min = 0.1
Max = 0.6


Statistics of Iris-versicolor:

Column: SepalLengthCm
Variance = 0.261104
Standard Deviation = 0.5109833656783751
Mean = 5.936
Median = 5.9
Min = 4.9
Max = 7.0


Column: SepalWidthCm
Variance = 0.0965
Standard Deviation = 0.31064449134018135
Mean = 2.7700000000000005
Median = 2.8
Min = 2.0
Max = 3.4


Column: PetalLengthCm
Variance = 0.21640000000000004
Standard Deviation = 0.4651881339845203
Mean = 4.26
Median = 4.35
Min = 3.0
Max = 5.1


Column: PetalWidthCm
Variance = 0.038324
Standard Deviation = 0.19576516544063705
Mean = 1.3259999999999998
Median = 1.3
Min = 1.0
Max = 1.8


Statistics of Iris-virginica:

Column: SepalLengthCm
Variance = 0.39625600000000005
Standard Deviation = 0.6294886813914926
Mean = 6.587999999999998
Median = 6.5
Min = 4.9
Max = 7.9


Column: SepalWidthCm
Variance = 0.10192399999999997
Standard Deviation = 0.31925538366643086
Mean = 2.974
Median = 3.0
Min = 2.2
Max = 3.8


Column: PetalLengthCm
Variance = 0.29849600000000004
Standard Deviation = 0.546347874526844
Mean = 5.5520000000000005
Median = 5.55
Min = 4.5
Max = 6.9


Column: PetalWidthCm
Variance = 0.07392399999999999
Standard Deviation = 0.2718896835115301
Mean = 2.0260000000000002
Median = 2.0
Min = 1.4
Max = 2.5